[options="header"]
[cols="1, 3, 3"]
|===
|Version | Bearbeitungsdatum   | Autor 
| 0.2    | 05.05.2024          | Jannik
|===

= Entwicklerdokumentation

== 1. Einführung und Ziele
=== Zieldefinition

Ziel dieser neuen webbasierten Kino-Allrounder-Software ist es, sowohl die Arbeitsprozesse der Mitarbeiter, autorisierten Mitarbeiter und des Bosses zu erleichtern, sowie als auch den Komfort und die Flexibilität der Kunden zu fördern. Die klassischen Vorgänge des ausschließlichen Vorort-Services, sowie die unübersichtliche, zeitintensive und nicht immer aktuelle Pflege von Ordner-Papier-Dokumenten für die Verwaltung, Organisation und strategische Planung sollen durch diese Software ersetzt und durch die Automatisierung für alle beteiligten Personen erleichtert werden.

In unserem Kino-System UFO spielen zum einen die Kunden (Customer) eine wesentliche Rolle. Diese können jederzeit über diese Anwendung über das Web sich das aktuelle Kinoprogramm  anzeigen lassen und nach Belieben bequem z.B. von Zuhause aus sich Plätze (Seat)s für eine kommende Veranstaltung (CinemaShow)s reservieren (Reservation) und diese dann vor Ort bis 30min vor der Veranstaltung kaufen.

Das System beinhaltet allerdings noch weitere Rollen (User), welche alle relational aufeinander aufbauen, was so viel bedeutet wie, jede Rolle mit einem höheren Status erlangt zusätzlich zu allen Rechten der unteren Rolle, weitere Rechte, um mit dem Kinosystem zu interagieren.

Als Erstes haben wir da den "normalen" Mitarbeiter, welcher die Verkaufsoberfläche des Systems nutzen kann, um z.B. Karten und Snacks zu verkaufen und Reservierungen vom Kunden (vor Ort / telefonisch) direkt anzulegen.

Dann gibt es den autorisierten Mitarbeiter, welcher neben den Aktionen des "normalen" Mitarbeiters zusätzlich noch Verwaltungsaufgaben im System einsehen, anlegen und ändern kann. Darunter zählt z.B. das Anpassen des Programms, Anbieter vergleichen, Zentrallager verwalten und aktuelle Filmstatistiken einsehen.

Die höchste Rolle besitzt der Chef, dieser kann alle Funktionen des Systems benutzen. Hierbei kommen administrative und operative Systemoptionen hinzu, wie z.B. das externe Vermieten von Sälen, die gesamte Personalverwaltung, das Anpassen von Preisen, sowie das Einsehen von Wirtschaftsdaten (Diagramme in einem Dashboard).

Alle Rollen sind dabei klar voneinander getrennt. Ein unregistrierter Nutzer kann dabei nur sich das Programm anzeigen lassen und sich neu registrieren (erhällt die Rolle des Kunden). Jeder Nutzer-Account besteht aus 3 Datenfeldern: E-Mail, Benutzername, Passwort. Die E-Mail dient dazu, damit ein Nutzer mit böswilligen Absichten sich nicht beliebig viele Nutzer-Accounts erstellt, um das Kino komplett mit Reservierungen auszubuchen. Dabei wird die E-Mail auf Validität geprüft und ebenfalls ob ein starkes Passwort vorhanden ist. Durch eine erfolgreiche Anmeldung erhällt der Nutzer seine jeweilige Rolle im System und dementsprechend die nötigen Rechte, um die aufgeführten UseCases auszuführen, zu können. Alle freigeschalteten Funktionen sind in der Navigationsbar auf der Startseite der Website des Kinos zentral durch Untermenüs aufrufbar. In jedem Untermenü kann eine oder mehrere Aktion(en) durchgeführt werden. Dies kann der Zugang zu Informationen sein, sowie das Editieren und Konfigurieren von aktuellen Geschehnissen im Kino. Zum Schutz vor unbefugtem Zugriff aus das System wird eine Nutzer-Session nach einer gewissen Zeit geschlossen und der Nutzer muss sich erneut anmelden.

Zusammenfassend soll eine solide, sichere, erweiterbare, zentrale webbasierte Kino-Allrounder Software entstehen, welche mehr Kunden anlocken soll und den Arbeitsaufwand des Personals und des Chefs verringern soll.


=== 1.2 Qualitätsanforderungen

Um die Qualität der Software beurteiln zu können, wurden die folgenden, durch die Software zu erfüllenden, Qualitätsmerkmale definiert:
Hinweis: Die nachfolgenden Erläuterungen wurden von https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO/IEC 25010 Software Quality Model^] und https://github.com/HOME-programming-pub/videoshop/blob/2aa60ddfa2ead70c23d8a655ff0f748e1fbec330/src/main/asciidoc/developer_documentation.adoc[HOME-programming-pub/videoshop] adaptiert.

Wartbarkeit::
Wartbarkeit bezeichnet den Grad an Effizienz, mit derer das System verbessert, korrigiert oder an neue Umgebungsbedingungen angepasst werden kann.

Nutzbarkeit::
Grad, zu dem das System durch die einzelnen Nutzergruppen effizient zum jeweiligen Nutzungszweck genutzt werden kann

Sicherheit::
Grad, zu derer das System Informationen, insbesondere personenbezogenen Daten, denjenigen Personden oder Systemen zeigt, die dafür autorisiert sind, und vor denjenigen verbirgt, die nicht autorisiert sind.

Die nachfolgende Tabelle zeigt die Qualitätsmerkmale sowie deren Wichtigkeit.
Die erste Spalte gibt den Namen des Qualitätsziels an, während in den Verbleibenden Spalten die Priorität durch dass
Vorhandensein einex "X" ausgewiesen wird. 1 entspricht einem Qualitätsmerkmal, das unwichtig ist, 5 einem, dass sehr wichtig ist.

[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Quality Demand           | 1 | 2 | 3 | 4 | 5
|Wartbarkeit              |   |   |   |   | X
|Nutzbarkeit              |   |   |   | X | 
|Sicherheit                 |   |   |   | X |
|===

== 2. Randbedingungen
* Hardware-Vorgaben
* Software-Vorgaben
* Vorgaben zum Betrieb des Software

== 3. Kontextabgrenzung
* Kontextdiagramm

== 4. Lösungsstrategie
=== 4.1 Erfüllung der Qualitätsziele
[options="header"]
|=== 
|Qualitätsziel |Lösungsansatz
|... |...
|===


=== 4.2 Softwarearchitektur
* Beschreibung der Architektur anhand der Top-Level-Architektur oder eines Client-Server-Diagramms

=== 4.3 Entwurfsentscheidungen
* Verwendete Muster
* Persistenz
* Benutzeroberfläche
* Verwendung externer Frameworks

[options="header", cols="1,2,3"]
|===
|Externes Package |Verwendet von |Warum
|... |... |...
|===

== 5. Bausteinsicht
* Package-Diagramm
* Entwurfsklassendiagramme der einzelnen Packages

[options="header"]
|=== 
|Klasse/Enumeration |Description
|... |...
|===

=== 5.1 Rückverfolgbarkeit zwischen Analyse- und Entwurfsmodell
_Die folgende Tabelle zeigt die Rückverfolgbarkeit zwischen Entwurfs- und Analysemodell._

[options="header"]
|===
|Klasse/Enumeration (Analysemodell) |Klasse/Enumeration (Entwurfsmodell)
|... |...
|===

== 6. Laufzeitsicht
* Darstellung der Komponenteninteraktion anhand eines Sequenzdiagramms, welches die relevantesten Interaktionen darstellt.


