= Entwicklerdokumentation
:project_name: Kinosystem UFO
:toc: left
:toc-title: Inhaltsverzeichnis
:numbered:


[options="header"]
[cols="1, 3, 3"]
|===
|Version | Bearbeitungsdatum   | Autor 
| 0.2    | 05.05.2024          | Jannik
|===



== Einführung und Ziele
=== Zieldefinition

Ziel dieser neuen webbasierten Kino-Allrounder-Software ist es, sowohl die Arbeitsprozesse der Mitarbeiter, autorisierten Mitarbeiter und des Bosses zu erleichtern, sowie als auch den Komfort und die Flexibilität der Kunden zu fördern. Die klassischen Vorgänge des ausschließlichen Vorort-Services, sowie die unübersichtliche, zeitintensive und nicht immer aktuelle Pflege von Ordner-Papier-Dokumenten für die Verwaltung, Organisation und strategische Planung sollen durch diese Software ersetzt und durch die Automatisierung für alle beteiligten Personen erleichtert werden.

In unserem Kino-System UFO spielen zum einen die Kunden (Customer) eine wesentliche Rolle. Diese können jederzeit über diese Anwendung über das Web sich das aktuelle Kinoprogramm  anzeigen lassen und nach Belieben bequem z.B. von Zuhause aus sich Plätze (Seat)s für eine kommende Veranstaltung (CinemaShow)s reservieren (Reservation) und diese dann vor Ort bis 30min vor der Veranstaltung kaufen.

Das System beinhaltet allerdings noch weitere Rollen (User), welche alle relational aufeinander aufbauen, was so viel bedeutet wie, jede Rolle mit einem höheren Status erlangt zusätzlich zu allen Rechten der unteren Rolle, weitere Rechte, um mit dem Kinosystem zu interagieren.

Als Erstes haben wir da den "normalen" Mitarbeiter, welcher die Verkaufsoberfläche des Systems nutzen kann, um z.B. Karten und Snacks zu verkaufen und Reservierungen vom Kunden (vor Ort / telefonisch) direkt anzulegen.

Dann gibt es den autorisierten Mitarbeiter, welcher neben den Aktionen des "normalen" Mitarbeiters zusätzlich noch Verwaltungsaufgaben im System einsehen, anlegen und ändern kann. Darunter zählt z.B. das Anpassen des Programms, Anbieter vergleichen, Zentrallager verwalten und aktuelle Filmstatistiken einsehen.

Die höchste Rolle besitzt der Chef, dieser kann alle Funktionen des Systems benutzen. Hierbei kommen administrative und operative Systemoptionen hinzu, wie z.B. das externe Vermieten von Sälen, die gesamte Personalverwaltung, das Anpassen von Preisen, sowie das Einsehen von Wirtschaftsdaten (Diagramme in einem Dashboard).

Alle Rollen sind dabei klar voneinander getrennt. Ein unregistrierter Nutzer kann dabei nur sich das Programm anzeigen lassen und sich neu registrieren (erhällt die Rolle des Kunden). Jeder Nutzer-Account besteht aus 3 Datenfeldern: E-Mail, Benutzername, Passwort. Die E-Mail dient dazu, damit ein Nutzer mit böswilligen Absichten sich nicht beliebig viele Nutzer-Accounts erstellt, um das Kino komplett mit Reservierungen auszubuchen. Dabei wird die E-Mail auf Validität geprüft und ebenfalls ob ein starkes Passwort vorhanden ist. Durch eine erfolgreiche Anmeldung erhällt der Nutzer seine jeweilige Rolle im System und dementsprechend die nötigen Rechte, um die aufgeführten UseCases auszuführen, zu können. Alle freigeschalteten Funktionen sind in der Navigationsbar auf der Startseite der Website des Kinos zentral durch Untermenüs aufrufbar. In jedem Untermenü kann eine oder mehrere Aktion(en) durchgeführt werden. Dies kann der Zugang zu Informationen sein, sowie das Editieren und Konfigurieren von aktuellen Geschehnissen im Kino. Zum Schutz vor unbefugtem Zugriff aus das System wird eine Nutzer-Session nach einer gewissen Zeit geschlossen und der Nutzer muss sich erneut anmelden.

Zusammenfassend soll eine solide, sichere, erweiterbare, zentrale webbasierte Kino-Allrounder Software entstehen, welche mehr Kunden anlocken soll und den Arbeitsaufwand des Personals und des Chefs verringern soll.


=== Qualitätsanforderungen

Um die Qualität der Software beurteiln zu können, wurden die folgenden, durch die Software zu erfüllenden, Qualitätsmerkmale definiert:
Hinweis: Die nachfolgenden Erläuterungen wurden von https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO/IEC 25010 Software Quality Model^] und https://github.com/HOME-programming-pub/videoshop/blob/2aa60ddfa2ead70c23d8a655ff0f748e1fbec330/src/main/asciidoc/developer_documentation.adoc[HOME-programming-pub/videoshop] adaptiert.

Wartbarkeit::
Wartbarkeit bezeichnet den Grad an Effizienz, mit derer das System verbessert, korrigiert oder an neue Umgebungsbedingungen angepasst werden kann.

Nutzbarkeit::
Grad, zu dem das System durch die einzelnen Nutzergruppen effizient zum jeweiligen Nutzungszweck genutzt werden kann

Sicherheit::
Grad, zu derer das System Informationen, insbesondere personenbezogenen Daten, denjenigen Personden oder Systemen zeigt, die dafür autorisiert sind, und vor denjenigen verbirgt, die nicht autorisiert sind.

Die nachfolgende Tabelle zeigt die Qualitätsmerkmale sowie deren Wichtigkeit.
Die erste Spalte gibt den Namen des Qualitätsziels an, während in den Verbleibenden Spalten die Priorität durch dass
Vorhandensein einex "X" ausgewiesen wird. 1 entspricht einem Qualitätsmerkmal, das unwichtig ist, 5 einem, dass sehr wichtig ist.

[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Quality Demand           | 1 | 2 | 3 | 4 | 5
|Wartbarkeit              |   |   |   |   | X
|Nutzbarkeit              |   |   |   | X | 
|Sicherheit                 |   |   |   | X |
|===

== Randbedingungen
=== Hardware Spezifikationen
Eine Liste der erforderlichen Geräte/Hardware zur Ausführung und Verwendung der Anwendung.

- Server
- Computer
- Tastatur
- Maus

=== Software Spezifikationen
Eine Liste der erforderlichen Software zur Ausführung und Verwendung der Anwendung.

Für die Ausführung der Anwendung ist die folgende (oder neuere) Java-Version erforderlich:

- Java 22

Zur Verwendung der Anwendung sind die folgenden (oder neuere) Browser-Versionen erforderlich:

- Edge 124.0
- Firefox 125.0
- Google Chrome 126.0
- Opera 109.0

=== Produktnutzung
Das System wird als eine Komplettlösung für eine Kinobetriebsgesellschaft genutzt. Diese enthält Teilsysteme zur Verwaltung, ein Kassensubsystem für den Verkauf sowie ein Kundenportal für Kunden. Diese Software wird von der Kinobetreibergesellschaft UFO in all ihren Standorten eingesetzt. Sie soll auf einem Server laufen und ist über das Internet (via Browser) für interessierte Kunden und der Kinobetreibergesellschaft UFO erreichbar.

Das Kundenportal kann intuitiv von Kunden genutzt werden, da sie das Navigationslayout einer typischen Webseite besitzt.
Das Kassensubsystem und das Verwaltungssystem wird wenig komplex und intuitiv bedienbar sein, wodurch sich die Mitarbeiter und der Chef schnell daran gewöhnen können.

Alle Daten sollen persistent in einer Datenbank gespeichert werden und über die Anwendung zugänglich sein (z.B. sollten Mitarbeiter  keine SQL-Anfragen formulieren müssen)

== Kontextabgrenzung
=== Kontextdiagramm
[[context_diagram_d_c4]]
image::./models/analysis/Kontext/Kontext.svg[Context diagram, 100%, 100%, pdfwidth=100%, title= "Kontextdiagramm des {project_name}", align=center]

== Lösungsstrategie
=== Erfüllung der Qualitätsziele
[options="header"]
|=== 
|Qualitätsziel |Lösungsansatz
|... |...
|===


=== Softwarearchitektur
* Beschreibung der Architektur anhand der Top-Level-Architektur oder eines Client-Server-Diagramms

=== Entwurfsentscheidungen
==== Verwendete Muster

==== Persistenz

==== Benutzeroberfläche


=== Verwendung externer Frameworks

[options="header", cols="1,2,3"]
|===
|Externes Package |Verwendet von |Warum
|... |... |...
|===

== Bausteinsicht
=== Package-Diagramm
NOTE: If your package structure is more nested as in this example, add an *UML package diagram* to this document. This diagram only shows the packages of the application, their containment structure, and \<<use>>-relationships between them. The goal is to give an overview of the detailed architecture._

_Example: https://www.uml-diagrams.org/multi-layered-web-architecture-uml-package-diagram-example.html_


=== Entwurfsklassendiagramme der einzelnen Packages

==== Kassensubsystem

[options="header"]
|=== 
|Klasse/Enumeration |Description
|... |...
|===


==== Kundenportal

[options="header"]
|===
|Klasse/Enumeration |Description
|... |...
|===


==== Verwaltungssystem

[options="header"]
|===
|Klasse/Enumeration |Description
|... |...
|===


==== Operativsystem

[options="header"]
|===
|Klasse/Enumeration |Description
|... |...
|===


==== Loginsystem

[options="header"]
|===
|Klasse/Enumeration |Description
|... |...
|===


=== Rückverfolgbarkeit zwischen Analyse- und Entwurfsmodell
_Die folgende Tabelle zeigt die Rückverfolgbarkeit zwischen Entwurfs- und Analysemodell._

[options="header"]
|===
|Klasse/Enumeration (Analysemodell) |Klasse/Enumeration (Entwurfsmodell)
|... |...
|===

== Laufzeitsicht
* Darstellung der Komponenteninteraktion anhand eines Sequenzdiagramms, welches die relevantesten Interaktionen darstellt.

=== Kassensubsystem


=== Kundenportal


=== Verwaltungssystem


=== Operativsystem

