= Nutzerhandbuch

:toc: left
:toc-title: Inhaltsverzeichnis
:numbered:

== Einleitung

...

== Systemanforderungen

Da das entwickelte System als Webserver im Internet läuft, sind hier sowohl 
die Anforderungen an den Server, der die Anwendung ausführt, als auch die Anforderungen an sich verbindende Clients angegeben.

=== Server

- Quadcore Prozessor mit 2GHz Taktrate
- 8GB RAM Arbeitsspeicher
- 4GB freien Festplattenspeicher
- Internetverbindung mit ausreichender Bandbreite
- Java 17 (oder eine neuere, abwärtskompatible Java-Version)

=== Clients

- Prozessor mit 1GHz Taktrate
- 2GB RAM Arbeitsspeicher
- 500MB freien Festplattenspeicher

Browser:

- Edge 124.0 oder neuer
- Firefox 126.0 oder neuer
- Google Chrome 126.0 oder neuer
- Opera 109.0 oder neuer

== Starten der Anwendung

Kopieren Sie das Jar in einen neuen Ordner, zu dem Sie Schreibrechte besitzen. Öffnen Sie ein Terminal im diesem Verzeichnis und führen Sie das jar mittels java -jar jarname.jar aus (Wenn das Jar beispielsweise cooleanwendung.jar heißt führen Sie java -jar cooleanwendung.jar aus).

Der Erststart dauert eventuell etwas länger, weil die Anwendung zusätzliche Bibliotheken herunterlädt.

Sobald die Anwendung gestartet ist, ist sie unter http://127.0.0.1:8080 erreichbar.

=== Datenbank-Administration

* ** Nutzername: 6c49af08a96d4b60bfcf57116182bb3a ** 
* ** Passwort: ecec3832a23246ed968480c2be0577e4**
* ** Admin-Zugangspasswort: ccff8eeeba824e5aa76b3646dab391b4 **

== Funktionen

Im nachfolgenden werden die wichtigsten Funktionen erläutert.

=== Loginsystem

...

==== Anmelden

Um sich anzumelden, gehen sie auf http://127.0.0.1:8080/login tragen ihren Nutzernamen und Passwort in die jeweiligen Felder ein und drücken auf Anmelden.

==== Registrieren

Um sich als Kunde zu registrieren gehen sie auf http://127.0.0.1:8080/registration füllen sie alle Felder aus und drücken sie auf registrieren. E-Mail und Nutzername dürfen noch nicht vergeben sein.

==== Nutzergruppen

[options="header"]
|===
|Name                 | Zugewiesene Rechte
| __Jeder__           | Startseite einsehen, Impressum einsehen, Datenschutzrichtlinie einsehen, Filmplan einsehen, anmelden, registrieren 
| Customer            | Zusätzlich zu __Jeder__: Reservierung anlegen, eigene Reservierung löschen, eigene Reservierungen anzeigen.
| EMPLOYEE            | Zusätzlich zum Customer: Tickets/Snacks verkaufen
| AUTHORIZED_EMPLOYEE | Zusätzlich zu EMPLOYEE: Programm verwalten, Filme ausleihen, Lager verwalten
| BOSS                | Zusätzlich zu AUTHORIZED_EMPLOYEE: Wirtschaftsstatistik einsehen, Saalverwaltung benutzen, Preise anpassen, Personal verwalten
|===

==== Initial angelegte Konten
[options="header"]
|===
|Name    | Passwort | Nutzergruppe
| boss    | 123      | BOSS
| em    | 123      | EMPLOYEE 
| aem    | 123      | AUTHORIZED_EMPLOYEE
| Test    | 123      | Customer
| user    | 123      | Customer 
|===

=== Kundenportal

...


==== Plätze Reservieren

Im System können sie mit zwei einfachen Schritten Plätze reservieren. Für die Reservierung müssen sie angemeldet sein. Jede logische Reservierung gilt immer nur für eine Veranstaltung (Film).
Im ersten Schritt müssen sie zunächst die Veranstaltung auswählen. Dazu haben Sie entweder die Möglichkeit, in der Programmverwaltung (http://127.0.0.1:8080/current-films) die für jeden nutzbaren
Reservieren-Links zu benutzen. Alternativ können Sie auch in der Navigation auf "Plätze reservieren" klicken. Sie landen dann auf einer Auswahlseite, wo sie die gewünschte Veranstaltung auswählen können.

Damit Sie eine Reservierung tätigen können, muss die Veranstaltung in der aktuellen oder kommenden Woche liegen und es müssen noch mindestends 45 Minuten bis zum Start sein.

Wenn Sie eine Veranstaltung ausgewählt haben, landen Sie auf einer Auswahlseite, wo Sie Tickets entfernen und hinzufügen können. Um ein Ticket zu entfernen klicken Sie auf den Löschen-Knopf innerhalb des Tickets. 
Um ein Ticket hinzuzufügen, wählen Sie aus der Maske den Tickettyp aus und Geben in das Eingabefeld oberhalb der Saalansicht den Platz ein. Gültige Plätze hängen vom Layout des Saals ab, Grundsätzlich sind jedoch 
A0, B1, C10 oder F1 gültige Plätze, während AA, 0A, 00 und F01 es nicht sind. Anschließend klicken Sie auf "Ticket hinzufügen" um das Ticket der Reservierung hinzuzufügen.

Wenn Sie ein Ticket ändern wollen, müssen Sie es Löschen und neu buchen.

Nicht-Mitarbeiter können maximal 10 Tickets reservieren.

Sobald Sie alle gewünschten Tickets ausgewählt haben, drücken Sie auf "Jetzt Reservieren" um den Reserviervorgang abzuschließen. Reservierungen ohne Tickets lassen sich nicht abschließen. Beachten Sie bitte, dass 45 Minuten vor Start keine Reservierungen mehr möglich sind. Beachten sie ferner, das alle Reservierungen 30 Minuten vor Start verfallen, wenn sie nicht abgeholt wurden.

==== Reservierung anzeigen

Um Reservierungen anzeigen zu können, müssen Sie im fraglichen Account eingeloggt sein. Sie sehen dann alle Reservierungen unter http://127.0.0.1:8080/my-reservations 

Um Reservierungen von anderen einsehen zu können, müssen sie als EMPLOYEE, AUTHORIZED_EMPLOYEE oder BOSS eingeloggt sein. Sie können dann auf 127.0.0.1:8080/reservations/find nach Reservierungen eines Nutzernamens oder E-Mail suchen.

==== Reservierung löschen

Sie können Reservierungen Löschen, in dem Sie in der Reservierungsansicht den Löschen-Link für die fragliche Reservierung klicken oder die Reservierungsnummer in das Formular unterhalb eingeben. In beiden Fällen wird die Reservierung nach einer Sicherheitsabfrage endgültig gelöscht.

==== Programm ansehen

Um das aktuelle Programm einzusehen, gehen Sie auf http://127.0.0.1:8080/current-films Um das Programm einer anderen Woche einzusehen, benutzen Sie bitte schriitweise die Mit Wochendaten beschrifteten Links für die Gewünschte Richtung.


=== Verwaltungssystem

...

==== Programm verwalten

Um das Programm verwalten zu können, müssen sie als AUTHORIZED_EMPLOYEE oder BOSS eingeloggt sein. Gehen sie zum hinzufügen von Programmpunkten auf http://127.0.0.1:8080/current-films
Um Programmpunkte zu ändern oder zu löschen, gehen sie auf obiger Seite auf den fraglichen Programmpunkt. Der Saal kann nur durch löschen und neuanlegen geändert werden, damit die Platzzuordnung funktioniert.
Wenn sie einen Programmpunkt löschen, beachten sie bitte, dass dadurch jegliche Reservierungen unwiederufflich gelöscht werden. Sie können keine Veranstaltung löschen, für die Tickets verkauft wurden. Sie können erst dann Veranstaltungen für einen
Film anlegen, wenn der Ticketpreis festgelegt wurde. Veranstaltungen dürfen sich einschließlich eines 10 min. Puffers davor und danach nicht überschneiden. Sie können keine 
Vorführung anlegen, wenn der Film im Fraglichen Zeitpunkt nicht entliehen wurde.

==== Filme ausleihen

Um Filme ausleihen zu können, müssen sie als AUTHORIZED_EMPLOYEE oder BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/rent-films 
Sie können den Verleihstatus nur für kommende Wochen ändern, und nur solange keine Vorführungen für den Fraglichen Film in der fraglichen Woche existieren.

==== Lagerverwaltung

Um das Lager verwalten zu können, müssen sie als AUTHORIZED_EMPLOYEE oder BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/manage/storage

=== Operativsystem

...

==== Saalverwaltung 

Um Säle verwalten zu können, müssen sie als BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/manage/rooms
Kinoprogramm wird über die Programmverwaltung verwaltet.

==== Wirtschaftsstatistik einsehen

Um die Wirtschaftsstatistik einsehen, müssen sie als BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/statistics


==== Preise anpassen

Um die Preise anpassen zu können, müssen sie als BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/manage/pricing


==== Personalverwaltung 

Um das Personal zu verwalten, müssen sie als BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/manage/staff

=== Kassensubsystem

...

==== Tickets verkaufen

Um Tickets zu verkaufen, müssen sie als EMPLOYEE, AUTHORIZED_EMPLOYEE oder BOSS eingeloggt sein. Gehen sie dann auf http://127.0.0.1:8080/sell-tickets wählen aus dem Dropdown die Gewünschte Veranstaltung aus und klicken Sie auf Weiter.
Sie können nur für Veranstaltungen dieser oder nächster Woche Tickets verkaufen. 

Wenn der Kunde ihnen eine Reservierungsnummer gibt, geben sie diese Nummer in das Eingabefeld "Reservierungsnummer" ein und drücken sie auf "Reservierung Laden",
um die Tickets dieser Reservierung zu laden.

Um ein Ticket zu entfernen klicken Sie auf den Löschen-Knopf innerhalb des Tickets. 
Um ein Ticket hinzuzufügen, wählen Sie aus der Maske den Tickettyp aus und Geben in das Eingabefeld oberhalb der Saalansicht den Platz ein. Gültige Plätze hängen vom Layout des Saals ab, Grundsätzlich sind jedoch 
A0, B1, C10 oder F1 gültige Plätze, während AA, 0A, 00 und F01 es nicht sind. Anschließend klicken Sie auf "Ticket hinzufügen" um das Ticket dem Warenkorb hinzuzufügen. Bereits belegte Plätze lassen sich nicht erneut verkaufen.

Zum Abschluss des Bezahlvorgangs klicken Sie auf "Kaufvorgang abschließen".
