= Pflichtenheft
:project_name: Projektname
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 01.04.2023          | Autor       | Initiale Version
|===

== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

== Produktnutzung
In welchem Kontext soll das System später genutzt werden? Welche Rahmenbedingungen gelten?
Zusätzlich kurze Einleitung für fachfremde Personen

== Interessensgruppen (Stakeholder)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|...  |...
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

- Karten verkaufen          AT
- Snacks verkaufen
- vor Ort/ telefonisch reservieren
- vor Ort/ telefonisch stornieren
- Online stornieren
- Online reservieren        AT
- Programm anzeigen
- Programm anpassen
- Anbieter vergleichen
- Zentrallager verwalten
- Filmbesucherstatistik einsehen
- Saal vermieten
- Personal verwalten
- Saal verwalten
- Preis anpassen
- Tageseinnahmen-Statistik einsehen
- Umsatzdiagramme einsehen
- Anmelden/Abmelden         AT
- Registrieren              AT

== Funktionale Anforderungen

=== Muss-Kriterien
[options="header", cols="2h, 1, 3, 12"]
|===
|ID
|Version
|Name
|Beschreibung

|[[F0010]]<<F0010>>
|v0.1
|Registrierung
a|
Neue Nutzer können sich registrieren.
mit folgenden Informationen:

* Nutzername
* E-Mail
* Password

|[[F0010]]<<F0010>>
|v0.1
|Überprüfung der Registrierung
a|
Überprüft Registrierung (E-Mail ...)
|[[F0010]]<<F0010>>
|v0.1
|Anmeldung
a|
Neue Nutzer können sich anmelden.
mit folgenden Informationen:

* Nutzername oder E-Mail
* Password

|[[F0010]]<<F0010>>
|v0.1
|Warenkorb
a|
Enthält Snacks und Film Tickets die der Kunde bislang ausgewählt hat.

|[[F0010]]<<F0010>>
|v0.1
|Hinzufügen zum Warenkorb
a|
Nutzer kann Snacks oder Film Tickets zum Warenkorb hinzufügen.

|[[F0010]]<<F0010>>
|v0.1
|Anzeigen zum Warenkorb
a|
Nutzer kann sich den Warenkorb anzeigen.

|[[F0010]]<<F0010>>
|v0.1
|Überprüfung der Reservierung
a|
Platz frei?

|[[F0010]]<<F0010>>
|v0.1
|Suche nach Reservierung
a|
Mitarbeiter sucht über die Reservierungsnummer (oder den Nutzernamen oder E-Mail des Kundens(KANN)) nach seiner Reservierung

|===




=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.


== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle

[cols="1h, 4"]
|===
|ID            |<<AT0010>> Neukunde registriert sich
|Use Case      |<<UC0010>> Registrieren
|Vorbedingung(en)      a|Ein unregistrierter Nutzer benutzt die Webseite.
|Ablauf      a|
Der unregistrierte Nutzer drückt auf "Registrieren" in der Webseiten Oberfläsche und trägt folgende Informationen in das Registrierungsformular ein:

- *Nutzername:* hans
- *Passwort:* passwort123
- *E-Mail:* hans_paswort123@mail.com

Anschließend drückt der Nutzer auf "Registrieren" unter dem Formular und senden damit die Informationen an das Loginsystem.
|Ergebniss(e)     a|
- Die Daten werden an das Loginsystem gesendet und geprüft ob die E-Mail bereits verwendet wurden ist
- Es wurde ein neuer Nutzer aus den übergebenen Daten erstellt und in der Datenbank des Logisystems hinterlegt
- Die Rolle des neuen Nutzerkontos ist: "Kunde"
- Dem Nutzer ist es nun möglich sich mit seinen Login Daten auf der Webseite anzumelden
- Der Nutzer ist immer noch unangemeldet und wird auf die Login Seite weitergeleitet
|===


[cols="1h, 4"]
|===
|ID            |<<AT0010>> Kunde meldet sich an
|Use Case      |<<UC0010>> Anmelden
|Vorbedingung(en)      a|Das Loginsystem hat existierende Nutzer.
|Ablauf      a|
Der Nutzer drückt auf "Login" in der Webseiten Oberfläsche und trägt folgende Informationen in das Login formular ein:

- *Nutzername:* hans
- *Passwort:* passwort123

Anschließend drückt der Nutzer auf "Login" unter dem Formular und senden damit die Informationen an das Loginsystem.
|Ergebniss(e)     a|
- Der Nutzer wird als "hans" angemeldet
- Der Nutzer erhält alle Berechtigungen die der Rolle des Nutzerkontos zugeordnet sind (in diesem Fall: "Kunde")
- Der Nutzer wird auf die Startseite weitergeleitet
|===

[cols="1h, 4"]
|===
|ID            |<<AT0010>> Kunde Reserviert Sitzplätze
|Use Case      |<<UC0010>> Online reservieren
|Vorbedingung(en)      a|Ein angemeldeter Nutzer nutzt die Webseite.
|Ablauf      a|
Der Kunde drückt auf "Plätze Reservieren" in der Webseiten Oberfläsche und fügt eine neue Reservierung zum "ReservierungsDashboard" hinzu. Im Resrvierungsformular wählt er zunächst die Vorführung un die Personen Anzahl aus
Anschließend __werden ihm passende Sitzplätze zugewiesen, die er allerdings ändern kann, indem er bestimmte Sitzplatznummern die er im darunter zu findenden Sitzplan sehen kann und in ein Textfeld kommasepariert eingeben muss (z.B: B2, B3, B4)__
Dann drückt der Nutzer auf "Senden"(__Im Sequenzdiagramm: "Speichern"__) unter dem Formular und senden damit die Informationen an das System.
|Ergebniss(e)     a|
- Es wird überprüft ob die Plätze noch verfügbar sind
- Da die Plätze verfügbar sind werden sie geschlossen als Reserviert im System eingetragen und können nun nicht mehr von anderen Kunden gebucht werden
- Der Kunde wird auf eine Reservierungsbestätigung-Seite weitergeleitet, auf der er deutlich seine Reservierungsnummer sehen kann
- __Mit der Reservierungsnummer kann der Mitarbeiter an der Kasse die reservierten Tickets aufrufen und nach Bezahlung dem Kunden ausstellen__
|===

[cols="1h, 4"]
|===
|ID            |<<AT0010>> Kunde möchte an der Kasse Karten kaufen ohne vorher Plätze reserviert zu haben
|Use Case      |<<UC0010>> Karten kaufen
|Vorbedingung(en)      a|Ein angemeldeter Mitarbeiter nutzt das Kassensubsystem
|Ablauf      a|
Der Mitarbeiter drückt auf __"neue Bestellung"__ und wählt zuerst eine der heutigen Vorstellungen, die der Kunde besuchen möchte. Danach wird die Platzart ausgewählt und die Anzahl der Personen angegeben.
|Ergebniss(e)     a|
- Wenn noch genug Plätze verfügbar sind werden die Tickets im Warenkorb abgelegt
- Anschließend wird man auf die __"Snackauswahl Seite"__ weitergeleitet. __Diese zeigt alle verfügbaren Menüs an__
|===

[cols="1h, 4"]
|===
|ID            |<<AT0010>> Kunde möchte an der Kasse Snacks während des Ticket kaufs
|Use Case      |<<UC0010>> Snacks kaufen
|Vorbedingung(en)      a|Ein angemeldeter Mitarbeiter nutzt das Kassensubsystem
|Ablauf      a|
Mitarbeiter wurde zur __"Snackauswahl Seite"__ weitergeleitet. Der Kunde möchte Menü 1 und Menü 2. Diese wählt der Mitarbeiter aus indem er auf das "+" unter den jeweiligen Menüs drückt. Anschließend drückt er auf "Bezahlen".
|Ergebniss(e)     a|
- Menü 1 und 2 wurden den Warenkorb hinzugefügt
- Es öffnet sich die Seite für den Warenkorb in dem die Bestellung in Rechnungsform zusammengefasst ist. Hier muss der Kunde bezahlen
- Nach kurzer Zubereitungszeit erhällt der Kunde die bestellten Snacks nach seinen Wünschen
|===



== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
