= Zeiterfassung für Gruppe XX

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche | Lukas Diettrich |Yannick Harnisch|Tobias Knoll|Simon Liepe|Jannik Schwaß| Meeting
|1 (01.04.2024 - 07.04.2024) |…   |…    |…    |…    |…    | 0
|2  |…   |…    |…    |…    |…    | 0
|3  |…   |…    |…    |…    |…    |3.25 
|4  |…   |…    |…    |…    |…    |1.1 
|5  |…   |…    |…    |…    |…    |1.25 
|6  |…   |…    |…    |…    |…    |0 
|7  |…   |…    |…    |…    |…    |1
|8  |…   |…    |…    |…    |…    |0
|9  |…   |…    |…    |…    |…    |0 
|10  |…   |…    |…    |…    |…    |0 
|11  |…   |…    |…    |…    |…    |0 
|12  |…   |…    |…    |…    |…    |0
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
