image:https://github.com/HOME-programming-lab/SP2024-G4-Kinobetreiber/actions/workflows/build.yml/badge.svg["CI Build", link="https://github.com/HOME-programming-lab/SP2024-G4-Kinobetreiber/actions"]

= Kinoverwaltungs- und Reservierungssystem UFO Kinos
== Wichtige Dokumente

* link:src/main/asciidoc/protocols[Meeting-Protokolle]: Meeting- und Reviewprotokolle.
* link:src/main/asciidoc/time_recording.adoc[Zeiterfassung]: eine Hilfestellung mit der Sie Ihre individuellen Arbeitszeiten erfassen können.
* link:src/main/asciidoc/pflichtenheft.adoc[Anforderungsspezifikation (Pflichtenheft)]
* link:src/main/asciidoc/developer_documentation.adoc[Entwicklerdokumentation (Software-Entwurf)]
* link:src/main/asciidoc/Endpoints.adoc[Endpunkte-Übersicht]
* link:src/main/asciidoc/Nutzerhandbuch.adoc[Nutzerhandbuch]

== Struktur des Repositories

Grundsätzlich entspricht die Projektstruktur dem Maven-Standardlayout. Sie finden daher die meisten wichtigen Artefakte unter `src/`:

  src/
  ├── main/
  │   ├── asciidoc/   -- Hier befinden sich die Nachweisdokumente und Anwendungsdokumentation (Asciidoc format)
  │   ├── java/       -- Hier befinden sich die Java-Quelldateien, in Java-Packages organisiert.
  │   └── resources/  -- Statische Elemente (wie z.B. Abbildungen und Stylesheets), https://www.thymeleaf.org/[Thymeleaf-Templates], etc.
  └── test/
      └── java/       -- Die automatischen Unit- und Integrationstests werden in einem separatem Verzeichnis abgelegt. Das ermöglicht es uns, die Testfälle sauber von der eigentlichen Anwendung zu trennen. Die Testfälle werden am Besten mit dem link:https://junit.org/junit5/[JUnit-Framework] erstellt.

=== Weitere Dateien:

* `.gitignore`          -- Dateien und Verzeichnisse, die nicht in das Repository eingecheckt werden sollen.
* `pom.xml`             -- Dies ist die Maven Build-Spezifikation, Informationen zu diesem Format finden Sie in der link:https://maven.apache.org/index.html[Maven-Dokumentation].
* `.editorconfig`       -- Erlaubt es, verschiedene Editoren mit identischen Grundeinstellungen zu versehen, z.B. bezüglich des Datei-Encodings, welches Sie standardmäßig am Besten auf UTF-8 stellen.
* `mvnw` und `mvnw.cmd` -- Shell-Skripte, die Maven herunterladen, installieren und ausführen, wenn es sich noch nicht auf Ihrem System befindet.

=== Cross-Testing

* link:Crosstesting%20Kleinreperaturbetrieb[Erhaltene Dateien]
** link:Crosstesting%20Kleinreperaturbetrieb/Kleinreparatur.jar[Kleinreparatur.jar]
** link:Crosstesting%20Kleinreperaturbetrieb/pflichtenheft.pdf[pflichtenheft.pdf]
** link:Crosstesting%20Kleinreperaturbetrieb/TestingManual.pdf[TestingManual.pdf]
* link:src/main/asciidoc/cross_testing_report_for_g5_kleinreparaturen.adoc[Report]

== Ausführen der Anwendung

* In der IDE (Eclipse): suchen Sie `Application.java`, Rechtsklick auf das Projekt und dann "Run As > Java Application"
* Von der Kommandozeile: `./mvnw spring-boot:run` ausführen

== Paketierung

Java-Anwendungen werden in der Regel als JAR-Dateien gepackt und ausgeliefert. Eine JAR-Datei kann von Javas virtueller Maschine direkt verarbeitet und ausgeführt werden, vorrausgesetzt in der JAR-Datei befindet sich eine Klasse mit einer `main`-Funktion, und diese ist im `Main-Class`-Attribut der Datei `/META-INF/MANIFEST.MF` des JAR's angegeben.
// vgl. https://stackoverflow.com/questions/9689793/cant-execute-jar-file-no-main-manifest-attribute?rq=2
// und  https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean

Maven unterstützt Sie auch bei der Erstellung solcher Paketierungen:

* Mittels `./mvnw clean package` erstellen Sie eine JAR-Datei im Build-Verzeichnis `target/`. 
* Die erstelle JAR-Datei kann dann mittels `java -jar $jarName` ausgeführt werden (`$jarName` steht für den Namen der erstellten Datei).
